EvalConf:
  multi_object: false
  max_steps: 1000
  max_dist: 1.0
  is_gibson: False
  object_nav_path: "converted_datasets"
  scene_path: "datasets/"
  log_rerun: True
  use_pointnav: False
  square_im: True
  use_subtask_manager: True

config: [
  ./controller_habitat.yaml,
  ./mapping_conf_sim.yaml,
  ./planning_conf.yaml
]